version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: gunicorn --config /etc/gunicorn.conf.py main:app
